package cpu

import "fmt"

func PrefixInstrucionFromByte(opcode byte) instruction {
	switch opcode {
	case 0x00:
		return &rlcB{}
	case 0x01:
		return &rlcC{}
	case 0x02:
		return &rlcD{}
	case 0x03:
		return &rlcE{}
	case 0x04:
		return &rlcH{}
	case 0x05:
		return &rlcL{}
	case 0x06:
		return &rlcDerefHL{}
	case 0x07:
		return &rlcA{}
	case 0x08:
		return &rrcB{}
	case 0x09:
		return &rrcC{}
	case 0x0a:
		return &rrcD{}
	case 0x0b:
		return &rrcE{}
	case 0x0c:
		return &rrcH{}
	case 0x0d:
		return &rrcL{}
	case 0x0e:
		return &rrcDerefHL{}
	case 0x0f:
		return &rrcA{}
	case 0x10:
		return &rlB{}
	case 0x11:
		return &rlC{}
	case 0x12:
		return &rlD{}
	case 0x13:
		return &rlE{}
	case 0x14:
		return &rlH{}
	case 0x15:
		return &rlL{}
	case 0x16:
		return &rlDerefHL{}
	case 0x17:
		return &rlA{}
	case 0x18:
		return &rrB{}
	case 0x19:
		return &rrC{}
	case 0x1a:
		return &rrD{}
	case 0x1b:
		return &rrE{}
	case 0x1c:
		return &rrH{}
	case 0x1d:
		return &rrL{}
	case 0x1e:
		return &rrDerefHL{}
	case 0x1f:
		return &rrA{}
	case 0x20:
		return &slaB{}
	case 0x21:
		return &slaC{}
	case 0x22:
		return &slaD{}
	case 0x23:
		return &slaE{}
	case 0x24:
		return &slaH{}
	case 0x25:
		return &slaL{}
	case 0x26:
		return &slaDerefHL{}
	case 0x27:
		return &slaA{}
	case 0x28:
		return &sraB{}
	case 0x29:
		return &sraC{}
	case 0x2a:
		return &sraD{}
	case 0x2b:
		return &sraE{}
	case 0x2c:
		return &sraH{}
	case 0x2d:
		return &sraL{}
	case 0x2e:
		return &sraDerefHL{}
	case 0x2f:
		return &sraA{}
	case 0x30:
		return &swapB{}
	case 0x31:
		return &swapC{}
	case 0x32:
		return &swapD{}
	case 0x33:
		return &swapE{}
	case 0x34:
		return &swapH{}
	case 0x35:
		return &swapL{}
	case 0x36:
		return &swapDerefHL{}
	case 0x37:
		return &swapA{}
	case 0x38:
		return &srlB{}
	case 0x39:
		return &srlC{}
	case 0x3a:
		return &srlD{}
	case 0x3b:
		return &srlE{}
	case 0x3c:
		return &srlH{}
	case 0x3d:
		return &srlL{}
	case 0x3e:
		return &srlDerefHL{}
	case 0x3f:
		return &srlA{}
	case 0x40:
		return &bit0B{}
	case 0x41:
		return &bit0C{}
	case 0x42:
		return &bit0D{}
	case 0x43:
		return &bit0E{}
	case 0x44:
		return &bit0H{}
	case 0x45:
		return &bit0L{}
	case 0x46:
		return &bit0DerefHL{}
	case 0x47:
		return &bit0A{}
	case 0x48:
		return &bit1B{}
	case 0x49:
		return &bit1C{}
	case 0x4a:
		return &bit1D{}
	case 0x4b:
		return &bit1E{}
	case 0x4c:
		return &bit1H{}
	case 0x4d:
		return &bit1L{}
	case 0x4e:
		return &bit1DerefHL{}
	case 0x4f:
		return &bit1A{}
	case 0x50:
		return &bit2B{}
	case 0x51:
		return &bit2C{}
	case 0x52:
		return &bit2D{}
	case 0x53:
		return &bit2E{}
	case 0x54:
		return &bit2H{}
	case 0x55:
		return &bit2L{}
	case 0x56:
		return &bit2DerefHL{}
	case 0x57:
		return &bit2A{}
	case 0x58:
		return &bit3B{}
	case 0x59:
		return &bit3C{}
	case 0x5a:
		return &bit3D{}
	case 0x5b:
		return &bit3E{}
	case 0x5c:
		return &bit3H{}
	case 0x5d:
		return &bit3L{}
	case 0x5e:
		return &bit3DerefHL{}
	case 0x5f:
		return &bit3A{}
	case 0x60:
		return &bit4B{}
	case 0x61:
		return &bit4C{}
	case 0x62:
		return &bit4D{}
	case 0x63:
		return &bit4E{}
	case 0x64:
		return &bit4H{}
	case 0x65:
		return &bit4L{}
	case 0x66:
		return &bit4DerefHL{}
	case 0x67:
		return &bit4A{}
	case 0x68:
		return &bit5B{}
	case 0x69:
		return &bit5C{}
	case 0x6a:
		return &bit5D{}
	case 0x6b:
		return &bit5E{}
	case 0x6c:
		return &bit5H{}
	case 0x6d:
		return &bit5L{}
	case 0x6e:
		return &bit5DerefHL{}
	case 0x6f:
		return &bit5A{}
	case 0x70:
		return &bit6B{}
	case 0x71:
		return &bit6C{}
	case 0x72:
		return &bit6D{}
	case 0x73:
		return &bit6E{}
	case 0x74:
		return &bit6H{}
	case 0x75:
		return &bit6L{}
	case 0x76:
		return &bit6DerefHL{}
	case 0x77:
		return &bit6A{}
	case 0x78:
		return &bit7B{}
	case 0x79:
		return &bit7C{}
	case 0x7a:
		return &bit7D{}
	case 0x7b:
		return &bit7E{}
	case 0x7c:
		return &bit7H{}
	case 0x7d:
		return &bit7L{}
	case 0x7e:
		return &bit7DerefHL{}
	case 0x7f:
		return &bit7A{}
	case 0x80:
		return &res0B{}
	case 0x81:
		return &res0C{}
	case 0x82:
		return &res0D{}
	case 0x83:
		return &res0E{}
	case 0x84:
		return &res0H{}
	case 0x85:
		return &res0L{}
	case 0x86:
		return &res0DerefHL{}
	case 0x87:
		return &res0A{}
	case 0x88:
		return &res1B{}
	case 0x89:
		return &res1C{}
	case 0x8a:
		return &res1D{}
	case 0x8b:
		return &res1E{}
	case 0x8c:
		return &res1H{}
	case 0x8d:
		return &res1L{}
	case 0x8e:
		return &res1DerefHL{}
	case 0x8f:
		return &res1A{}
	case 0x90:
		return &res2B{}
	case 0x91:
		return &res2C{}
	case 0x92:
		return &res2D{}
	case 0x93:
		return &res2E{}
	case 0x94:
		return &res2H{}
	case 0x95:
		return &res2L{}
	case 0x96:
		return &res2DerefHL{}
	case 0x97:
		return &res2A{}
	case 0x98:
		return &res3B{}
	case 0x99:
		return &res3C{}
	case 0x9a:
		return &res3D{}
	case 0x9b:
		return &res3E{}
	case 0x9c:
		return &res3H{}
	case 0x9d:
		return &res3L{}
	case 0x9e:
		return &res3DerefHL{}
	case 0x9f:
		return &res3A{}
	case 0xa0:
		return &res4B{}
	case 0xa1:
		return &res4C{}
	case 0xa2:
		return &res4D{}
	case 0xa3:
		return &res4E{}
	case 0xa4:
		return &res4H{}
	case 0xa5:
		return &res4L{}
	case 0xa6:
		return &res4DerefHL{}
	case 0xa7:
		return &res4A{}
	case 0xa8:
		return &res5B{}
	case 0xa9:
		return &res5C{}
	case 0xaa:
		return &res5D{}
	case 0xab:
		return &res5E{}
	case 0xac:
		return &res5H{}
	case 0xad:
		return &res5L{}
	case 0xae:
		return &res5DerefHL{}
	case 0xaf:
		return &res5A{}
	case 0xb0:
		return &res6B{}
	case 0xb1:
		return &res6C{}
	case 0xb2:
		return &res6D{}
	case 0xb3:
		return &res6E{}
	case 0xb4:
		return &res6H{}
	case 0xb5:
		return &res6L{}
	case 0xb6:
		return &res6DerefHL{}
	case 0xb7:
		return &res6A{}
	case 0xb8:
		return &res7B{}
	case 0xb9:
		return &res7C{}
	case 0xba:
		return &res7D{}
	case 0xbb:
		return &res7E{}
	case 0xbc:
		return &res7H{}
	case 0xbd:
		return &res7L{}
	case 0xbe:
		return &res7DerefHL{}
	case 0xbf:
		return &res7A{}
	case 0xc0:
		return &set0B{}
	case 0xc1:
		return &set0C{}
	case 0xc2:
		return &set0D{}
	case 0xc3:
		return &set0E{}
	case 0xc4:
		return &set0H{}
	case 0xc5:
		return &set0L{}
	case 0xc6:
		return &set0DerefHL{}
	case 0xc7:
		return &set0A{}
	case 0xc8:
		return &set1B{}
	case 0xc9:
		return &set1C{}
	case 0xca:
		return &set1D{}
	case 0xcb:
		return &set1E{}
	case 0xcc:
		return &set1H{}
	case 0xcd:
		return &set1L{}
	case 0xce:
		return &set1DerefHL{}
	case 0xcf:
		return &set1A{}
	case 0xd0:
		return &set2B{}
	case 0xd1:
		return &set2C{}
	case 0xd2:
		return &set2D{}
	case 0xd3:
		return &set2E{}
	case 0xd4:
		return &set2H{}
	case 0xd5:
		return &set2L{}
	case 0xd6:
		return &set2DerefHL{}
	case 0xd7:
		return &set2A{}
	case 0xd8:
		return &set3B{}
	case 0xd9:
		return &set3C{}
	case 0xda:
		return &set3D{}
	case 0xdb:
		return &set3E{}
	case 0xdc:
		return &set3H{}
	case 0xdd:
		return &set3L{}
	case 0xde:
		return &set3DerefHL{}
	case 0xdf:
		return &set3A{}
	case 0xe0:
		return &set4B{}
	case 0xe1:
		return &set4C{}
	case 0xe2:
		return &set4D{}
	case 0xe3:
		return &set4E{}
	case 0xe4:
		return &set4H{}
	case 0xe5:
		return &set4L{}
	case 0xe6:
		return &set4DerefHL{}
	case 0xe7:
		return &set4A{}
	case 0xe8:
		return &set5B{}
	case 0xe9:
		return &set5C{}
	case 0xea:
		return &set5D{}
	case 0xeb:
		return &set5E{}
	case 0xec:
		return &set5H{}
	case 0xed:
		return &set5L{}
	case 0xee:
		return &set5DerefHL{}
	case 0xef:
		return &set5A{}
	case 0xf0:
		return &set6B{}
	case 0xf1:
		return &set6C{}
	case 0xf2:
		return &set6D{}
	case 0xf3:
		return &set6E{}
	case 0xf4:
		return &set6H{}
	case 0xf5:
		return &set6L{}
	case 0xf6:
		return &set6DerefHL{}
	case 0xf7:
		return &set6A{}
	case 0xf8:
		return &set7B{}
	case 0xf9:
		return &set7C{}
	case 0xfa:
		return &set7D{}
	case 0xfb:
		return &set7E{}
	case 0xfc:
		return &set7H{}
	case 0xfd:
		return &set7L{}
	case 0xfe:
		return &set7DerefHL{}
	case 0xff:
		return &set7A{}
	default:
		panic(fmt.Sprintf("Unknown opcode: 0x%02x", opcode))
	}
}
